---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/kube-system/cilium/ks.yaml
  - ../../apps/kube-system/coredns/ks.yaml
  - ../../apps/kube-system/descheduler/ks.yaml
  - ../../apps/kube-system/metrics-server/ks.yaml
  - ../../apps/kube-system/reloader/ks.yaml
  - ../../apps/kube-system/snapshot-controller/ks.yaml
  - ../../apps/kube-system/spegel/ks.yaml
  - ../../apps/cert-manager
  - ../../apps/external-secrets
  - ../../apps/flux-system
  - ../../apps/network
  - ../../apps/default/autobrr/ks.yaml
  - ../../apps/default/prowlarr/ks.yaml
  - ../../apps/default/qbittorrent/ks.yaml
  - ../../apps/default/radarr/ks.yaml
  - ../../apps/default/sabnzbd/ks.yaml
  - ../../apps/default/seerr/ks.yaml
  - ../../apps/default/sonarr/ks.yaml
  - ../../apps/default/bazarr/ks.yaml
  - ../../apps/default/tautulli/ks.yaml
  - ../../apps/openebs-system/openebs/ks.yaml
  - ../../apps/system-upgrade
