---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        credentials.json: |-
          {{ toJson (dict "AccountTag" .CLOUDFLARE_ACCOUNT_TAG "TunnelID" "${CLOUDFLARE_TUNNEL_ID}" "TunnelSecret" .CLOUDFLARE_TUNNEL_SECRET) }}
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_TAG
      remoteRef:
        key: "${CLOUDFLARE_BITWARDEN_ITEM_ID}"
        property: CLOUDFLARE_ACCOUNT_TAG
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: "${CLOUDFLARE_BITWARDEN_ITEM_ID}"
        property: CLOUDFLARE_TUNNEL_SECRET
