---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${PVC_CAPACITY:=5Gi}
  storageClassName: ${PVC_STORAGECLASS:=openebs-hostpath}
